### PR TITLE
Galloping grill and gameinform fix

### PR DESCRIPTION
**Pull request by soolar**
Makes galloping grill take precedence over sombrero (since it's a sombrero but better) and fixes gameinform support.

### CODE REVIEW

**Comment by Malurth** [comment]
The visit_url URL is wrong:<pre>pwd</pre> needs to be <pre>pwd="+my_hash()+"</pre>

Fix that and I'll merge it.

**Comment by soolar** [comment]
Mafia automatically corrects it since it's such a common thing. Or at least, I'm 99% sure it does, because I ran that line of code and it worked.

**Comment by coderanger** [comment]
```
In a POST request, if &pwd is part of the page string, it will automatically be replaced
by &pwd=###### where ###### is the password hash for the current session. For a
GET request the password hash will not be added so you'll want to use my_hash(). 
```

**Comment by soolar** [comment]
Yep, and it's POST by default.

**Comment by Malurth** [comment]
All right then, never mind. I stand corrected.

**Comment by Malurth** [comment]
Also thanks :p

**Pull request merged**
